### ISSUE TITLE
Set up a Travis CI pipeline that runs linting tests and calculates code coverage

### ISSUE THREAD

**Issue by sarthak-sopho** [elixir-cloud-aai/archetype-flask-connexion#14]
Set up a Travis CI pipeline that runs

- linting tests, `pytest`
- calculates the test coverage and interfaces with `coveralls`.

**Comment by uniqueg** [comment]
Compare Travis config in [TEStribute](https://github.com/elixir-cloud-aai/TEStribute) for a start.

See #6 to see how to add a badge for code coverage based on the [`coveralls`](https://coveralls.io) report.
