### ISSUE TITLE
Add config modules

### ISSUE THREAD

**Issue by sarthak-sopho** [elixir-cloud-aai/archetype-flask-connexion#8]
Check if there are differences between the Python modules in the following (sub)packages:
- https://github.com/elixir-europe/WES-ELIXIR/tree/dev/wes_elixir/config
- https://github.com/elixir-europe/proTES/tree/dev/pro_tes/config
- https://github.com/elixir-europe/proWES/tree/master/pro_wes/config

If there are differences, summarize and discuss differences. If not, add modules to archetype (adjusting import paths).

**Comment by uniqueg** [comment]
I've just looked at it, and I think that apart from `config_parser.py`, we could also use the `log_config.py` and `app_config.py` modules. It might also be good to include `log_config.yaml` as a reasonable default. The app config file on the other hand is too specific to each service, so I think for now we should skip that. Perhaps we could include some parts of it later as defaults, if we find that there are thing that always go in each service.
